### ISSUE TITLE
Q: Comparison with kd-tree?

### ISSUE THREAD

**Issue by ib00** [InteractiveComputerGraphics/TreeNSearch#1]
How does performance compare to a kd-tree?

In particular, I am wondering if this data structure could be used for example for photon mapping.

**Comment by JoseAntFer** [comment]
Hello,

I am not sure if TreeNSearch can even be used for photon mapping since, as far as I understand it, you would need to do queries with rays and we do not support rays. TreeNSearch exclusively works with point clouds and its goal is to find neighbors between the points.

**Comment by JoseAntFer** [comment]
I don't want to make any absolute claims about the efficiency of different data structures for different applications. In our very specific case, the neighborhood search stage in SPH simulations with millions of particles, using an octree was faster than a kdtree. But we had to implement both and try out to be sure about this. So I would encourage you to do the same if you need that extra performance.

On the topic of using TreeNSearch for your application, well that depends on whether your application fits the type of problem that TreeNSearch was designed for. You can find this at the end of the README: "TreeNSeach is optimized to be run many times as points move very little between runs". Also, keep in mind that you cannot query TreeNSearch on a per-point basis and that it doesn't find n nearest neighbors, it only finds neighbors within a radius. So, in conclusion, if your problem is "I have a lot of points and I need the list of neighbors within a given search radius of every one of these points", then you can use TreeNSearch. Otherwise I am afraid it is not the tool you are looking for :)

Best regards.
José.

**Comment by ib00** [comment]
Thanks! I'll try it out.

For a photon map application, the photon map (millions of points) is built once and then queried thousands of times. So, TreeNSearch fits, I believe.

**Comment by JoseAntFer** [comment]
Sounds good! 
As a final note, keep in mind that TreeNSearch only works when all the query points are known at the same time. In other words, you cannot query for neighbors for a single point (at least not efficiently). 

The way I imagine this would work for you is to declare the points that make up your photon map as one point set and all the query points as another point set. Set TreeNSearch to search from the query points set into the photon map set. This way you get the neighbors for all the query points in one go.

**Comment by ForrestLeee** [comment]
Does it run on a GPU ?  Thanks.

**Comment by JoseAntFer** [comment]
TreeNSearch is exclusive to CPU.
